version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: vbee-oms-db
    restart: unless-stopped
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - vbee-oms-network

  server:
    build:
      context: ./server
      target: ${STAGE}
    container_name: vbee-oms-server
    working_dir: /usr/src/app
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file: ./server/.env
    command: yarn dev
    networks:
      - vbee-oms-network

  client:
    build:
      context: ./client
      target: ${STAGE}
    container_name: vbee-oms-client
    working_dir: /usr/src/app
    restart: unless-stopped
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start
    networks:
      - vbee-oms-network

networks:
  vbee-oms-network:
    driver: bridge
    name: vbee-oms-network
