const ServiceActionTypes = {
  FETCH_ALL_SERVICES_START: 'FETCH_ALL_SERVICES_START',
  FETCH_ALL_SERVICES_SUCCESS: 'FETCH_ALL_SERVICES_SUCCESS',
  FETCH_ALL_SERVICES_FAILURE: 'FETCH_ALL_SERVICES_FAILURE',

  FETCH_SERVICE_START: 'FETCH_SERVICE_START',
  FETCH_SERVICE_SUCCESS: 'FETCH_SERVICE_SUCCESS',
  FETCH_SERVICE_FAILURE: 'FETCH_SERVICE_FAILURE',

  CREATE_SERVICE_START: 'CREATE_SERVICE_START',
  CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
  CREATE_SERVICE_FAILURE: 'CREATE_SERVICE_FAILURE',

  UPDATE_SERVICE_START: 'UPDATE_SERVICE_START',
  UPDATE_SERVICE_SUCCESS: 'UPDATE_SERVICE_SUCCESS',
  UPDATE_SERVICE_FAILURE: 'UPDATE_SERVICE_FAILURE',

  DELETE_SERVICE_START: 'DELETE_SERVICE_START',
  DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
  DELETE_SERVICE_FAILURE: 'DELETE_SERVICE_FAILURE',

  SET_CURRENT_SERVICE: 'SET_CURRENT_SERVICE',

  SET_CURRENT_SERVICE_MEMBER: 'SET_CURRENT_SERVICE_MEMBER',

  ADD_SERVICE_MEMBER_START: 'ADD_SERVICE_MEMBER_START',
  ADD_SERVICE_MEMBER_SUCCESS: 'ADD_SERVICE_MEMBER_SUCCESS',
  ADD_SERVICE_MEMBER_FAILURE: 'ADD_SERVICE_MEMBER_FAILURE',

  UPDATE_SERVICE_MEMBER_START: 'UPDATE_SERVICE_MEMBER_START',
  UPDATE_SERVICE_MEMBER_SUCCESS: 'UPDATE_SERVICE_MEMBER_SUCCESS',
  UPDATE_SERVICE_MEMBER_FAILURE: 'UPDATE_SERVICE_MEMBER_FAILURE',

  REMOVE_SERVICE_MEMBER_START: 'REMOVE_SERVICE_MEMBER_START',
  REMOVE_SERVICE_MEMBER_SUCCESS: 'REMOVE_SERVICE_MEMBER_SUCCESS',
  REMOVE_SERVICE_MEMBER_FAILURE: 'REMOVE_SERVICE_MEMBER_FAILURE'
};

export default ServiceActionTypes;
