const ClusterActionTypes = {
  FETCH_ALL_CLUSTERS_START: 'FETCH_ALL_CLUSTERS_START',
  FETCH_ALL_CLUSTERS_SUCCESS: 'FETCH_ALL_CLUSTERS_SUCCESS',
  FETCH_ALL_CLUSTERS_FAILURE: 'FETCH_ALL_CLUSTERS_FAILURE',

  FETCH_CLUSTER_START: 'FETCH_CLUSTER_START',
  FETCH_CLUSTER_SUCCESS: 'FETCH_CLUSTER_SUCCESS',
  FETCH_CLUSTER_FAILURE: 'FETCH_CLUSTER_FAILURE',

  CREATE_CLUSTER_START: 'CREATE_CLUSTER_START',
  CREATE_CLUSTER_SUCCESS: 'CREATE_CLUSTER_SUCCESS',
  CREATE_CLUSTER_FAILURE: 'CREATE_CLUSTER_FAILURE',

  UPDATE_CLUSTER_INFO_START: 'UPDATE_CLUSTER_INFO_START',
  UPDATE_CLUSTER_INFO_SUCCESS: 'UPDATE_CLUSTER_INFO_SUCCESS',
  UPDATE_CLUSTER_INFO_FAILURE: 'UPDATE_CLUSTER_INFO_FAILURE',

  DELETE_CLUSTER_START: 'DELETE_CLUSTER_START',
  DELETE_CLUSTER_SUCCESS: 'DELETE_CLUSTER_SUCCESS',
  DELETE_CLUSTER_FAILURE: 'DELETE_CLUSTER_FAILURE',

  SET_CURRENT_CLUSTER_MEMBER: 'SET_CURRENT_CLUSTER_MEMBER',

  ADD_CLUSTER_MEMBER_START: 'ADD_CLUSTER_MEMBER_START',
  ADD_CLUSTER_MEMBER_SUCCESS: 'ADD_CLUSTER_MEMBER_SUCCESS',
  ADD_CLUSTER_MEMBER_FAILURE: 'ADD_CLUSTER_MEMBER_FAILURE',

  UPDATE_CLUSTER_MEMBER_START: 'UPDATE_CLUSTER_MEMBER_START',
  UPDATE_CLUSTER_MEMBER_SUCCESS: 'UPDATE_CLUSTER_MEMBER_SUCCESS',
  UPDATE_CLUSTER_MEMBER_FAILURE: 'UPDATE_CLUSTER_MEMBER_FAILURE',

  REMOVE_CLUSTER_MEMBER_START: 'REMOVE_CLUSTER_MEMBER_START',
  REMOVE_CLUSTER_MEMBER_SUCCESS: 'REMOVE_CLUSTER_MEMBER_SUCCESS',
  REMOVE_CLUSTER_MEMBER_FAILURE: 'REMOVE_CLUSTER_MEMBER_FAILURE',

  ADD_SERVICE: 'ADD_SERVICE'
};

export default ClusterActionTypes;
