const ServerActionTypes = {
  FETCH_ALL_SERVERS_START: 'FETCH_ALL_SERVERS_START',
  FETCH_ALL_SERVERS_SUCCESS: 'FETCH_ALL_SERVERS_SUCCESS',
  FETCH_ALL_SERVERS_FAILURE: 'FETCH_ALL_SERVERS_FAILURE',

  FETCH_SERVER_START: 'FETCH_SERVER_START',
  FETCH_SERVER_SUCCESS: 'FETCH_SERVER_SUCCESS',
  FETCH_SERVER_FAILURE: 'FETCH_SERVER_FAILURE',

  CREATE_SERVER_START: 'CREATE_SERVER_START',
  CREATE_SERVER_SUCCESS: 'CREATE_SERVER_SUCCESS',
  CREATE_SERVER_FAILURE: 'CREATE_SERVER_FAILURE',

  UPDATE_SERVER_START: 'UPDATE_SERVER_START',
  UPDATE_SERVER_SUCCESS: 'UPDATE_SERVER_SUCCESS',
  UPDATE_SERVER_FAILURE: 'UPDATE_SERVER_FAILURE',

  DELETE_SERVER_START: 'DELETE_SERVER_START',
  DELETE_SERVER_SUCCESS: 'DELETE_SERVER_SUCCESS',
  DELETE_SERVER_FAILURE: 'DELETE_SERVER_FAILURE',

  SET_CURRENT_SERVER: 'SET_CURRENT_SERVER',

  FETCH_SERVERS_METRICS_START: 'FETCH_SERVERS_METRICS_START',
  FETCH_SERVERS_METRICS_SUCCESS: 'FETCH_SERVERS_METRICS_SUCCESS',
  FETCH_SERVERS_METRICS_FAILURE: 'FETCH_SERVERS_METRICS_FAILURE',

  SET_CURRENT_SERVER_DOMAIN: 'SET_CURRENT_SERVER_DOMAIN',

  GET_ALL_SERVER_DOMAINS_SSL_STATUS_START:
    'GET_ALL_SERVER_DOMAINS_SSL_STATUS_START',
  GET_ALL_SERVER_DOMAINS_SSL_STATUS_SUCCESS:
    'GET_ALL_SERVER_DOMAINS_SSL_STATUS_SUCCESS',
  GET_ALL_SERVER_DOMAINS_SSL_STATUS_FAILURE:
    'GET_ALL_SERVER_DOMAINS_SSL_STATUS_FAILURE',

  GET_DOMAINS_SSL_STATUS_START: 'GET_DOMAINS_SSL_STATUS_START',
  GET_DOMAINS_SSL_STATUS_SUCCESS: 'GET_DOMAINS_SSL_STATUS_SUCCESS',
  GET_DOMAINS_SSL_STATUS_FAILURE: 'GET_DOMAINS_SSL_STATUS_FAILURE',

  ADD_SERVER_DOMAINS_START: 'ADD_SERVER_DOMAINS_START',
  ADD_SERVER_DOMAINS_SUCCESS: 'ADD_SERVER_DOMAINS_SUCCESS',
  ADD_SERVER_DOMAINS_FAILURE: 'ADD_SERVER_DOMAINS_FAILURE',

  UPDATE_SERVER_DOMAIN_START: 'UPDATE_SERVER_DOMAIN_START',
  UPDATE_SERVER_DOMAIN_SUCCESS: 'UPDATE_SERVER_DOMAIN_SUCCESS',
  UPDATE_SERVER_DOMAIN_FAILURE: 'UPDATE_SERVER_DOMAIN_FAILURE',

  REMOVE_SERVER_DOMAIN_START: 'REMOVE_SERVER_DOMAIN_START',
  REMOVE_SERVER_DOMAIN_SUCCESS: 'REMOVE_SERVER_DOMAIN_SUCCESS',
  REMOVE_SERVER_DOMAIN_FAILURE: 'REMOVE_SERVER_DOMAIN_FAILURE'
};

export default ServerActionTypes;
