const ModalActionTypes = {
  SET_PREFERENCES_MODAL_OPEN: 'SET_PREFERENCES_MODAL_OPEN',

  SET_CLUSTER_CREATION_MODAL_OPEN: 'SET_CLUSTER_CREATION_MODAL_OPEN',
  SET_CLUSTER_DELETE_CONFIRMATION_MODAL_OPEN:
    'SET_CLUSTER_DELETE_CONFIRMATION_MODAL_OPEN',
  SET_CLUSTER_MEMBER_ADDITION_MODAL_OPEN:
    'SET_CLUSTER_MEMBER_ADDITION_MODAL_OPEN',
  SET_CLUSTER_MEMBER_REMOVAL_CONFIRMATION_MODAL_OPEN:
    'SET_CLUSTER_MEMBER_REMOVAL_CONFIRMATION_MODAL_OPEN',

  SET_SERVER_CREATION_MODAL_OPEN: 'SET_SERVER_CREATION_MODAL_OPEN',
  SET_SERVER_DELETE_CONFIRMATION_MODAL_OPEN:
    'SET_SERVER_DELETE_CONFIRMATION_MODAL_OPEN',
  SET_SERVER_DOMAIN_ADDITION_MODAL_OPEN:
    'SET_SERVER_DOMAIN_ADDITION_MODAL_OPEN',
  SET_SERVER_DOMAIN_UPDATE_MODAL_OPEN: 'SET_SERVER_DOMAIN_UPDATE_MODAL_OPEN',
  SET_SERVER_DOMAIN_REMOVAL_CONFIRMATION_MODAL_OPEN:
    'SET_SERVER_DOMAIN_REMOVAL_CONFIRMATION_MODAL_OPEN',

  SET_REPOSITORY_MEMBER_ADDITION_MODAL_OPEN:
    'SET_REPOSITORY_MEMBER_ADDITION_MODAL_OPEN',
  SET_REPOSITORY_MEMBER_REMOVAL_CONFIRMATION_MODAL_OPEN:
    'SET_REPOSITORY_MEMBER_REMOVAL_CONFIRMATION_MODAL_OPEN',

  SET_SERVICE_CREATION_MODAL_OPEN: 'SET_SERVICE_CREATION_MODAL_OPEN',
  SET_SERVICE_DELETE_CONFIRMATION_MODAL_OPEN:
    'SET_SERVICE_DELETE_CONFIRMATION_MODAL_OPEN',
  SET_SERVICE_MEMBER_ADDITION_MODAL_OPEN:
    'SET_SERVICE_MEMBER_ADDITION_MODAL_OPEN',
  SET_SERVICE_MEMBER_REMOVAL_CONFIRMATION_MODAL_OPEN:
    'SET_SERVICE_MEMBER_REMOVAL_CONFIRMATION_MODAL_OPEN',

  SET_CLUSTER_DIAGRAM_NODE_REMOVAL_CONFIRMATION_MODAL_OPEN:
    'SET_CLUSTER_DIAGRAM_NODE_REMOVAL_CONFIRMATION_MODAL_OPEN',
  SET_CLUSTER_DIAGRAM_ELEMENTS_REMOVAL_CONFIRMATION_MODAL_OPEN:
    'SET_CLUSTER_DIAGRAM_ELEMENTS_REMOVAL_CONFIRMATION_MODAL_OPEN',

  SET_USER_CREATION_MODAL_OPEN: 'SET_USER_CREATION_MODAL_OPEN',
  SET_USER_DELETE_CONFIRMATION_MODAL_OPEN:
    'SET_USER_DELETE_CONFIRMATION_MODAL_OPEN',
  SET_REMOVING_USER_FROM_ALL_CLUSTERS_CONFIRMATION_MODAL_OPEN:
    'SET_REMOVING_USER_FROM_ALL_CLUSTERS_CONFIRMATION_MODAL_OPEN',
  SET_REMOVING_USER_FROM_ALL_SERVICES_CONFIRMATION_MODAL_OPEN:
    'SET_REMOVING_USER_FROM_ALL_SERVICES_CONFIRMATION_MODAL_OPEN',
  SET_REMOVING_USER_FROM_ALL_REPOS_CONFIRMATION_MODAL_OPEN:
    'SET_REMOVING_USER_FROM_ALL_REPOS_CONFIRMATION_MODAL_OPEN'
};

export default ModalActionTypes;
