const DiagramActionTypes = {
  FETCH_CLUSTER_DIAGRAM_START: 'FETCH_CLUSTER_DIAGRAM_START',
  FETCH_CLUSTER_DIAGRAM_SUCCESS: 'FETCH_CLUSTER_DIAGRAM_SUCCESS',
  FETCH_CLUSTER_DIAGRAM_FAILURE: 'FETCH_CLUSTER_DIAGRAM_FAILURE',

  SET_SELECTED_DIAGRAM_NODE: 'SET_SELECTED_DIAGRAM_NODE',
  SET_SELECTED_DIAGRAM_ELEMENTS: 'SET_SELECTED_DIAGRAM_ELEMENTS',

  UPDATE_CLUSTER_DIAGRAM_ELEMENTS_START:
    'UPDATE_CLUSTER_DIAGRAM_ELEMENTS_START',
  UPDATE_CLUSTER_DIAGRAM_ELEMENTS_SUCCESS:
    'UPDATE_CLUSTER_DIAGRAM_ELEMENTS_SUCCESS',
  UPDATE_CLUSTER_DIAGRAM_ELEMENTS_FAILURE:
    'UPDATE_CLUSTER_DIAGRAM_ELEMENTS_FAILURE',

  REMOVE_CLUSTER_DIAGRAM_ELEMENTS_START:
    'REMOVE_CLUSTER_DIAGRAM_ELEMENTS_START',
  REMOVE_CLUSTER_DIAGRAM_ELEMENTS_SUCCESS:
    'REMOVE_CLUSTER_DIAGRAM_ELEMENTS_SUCCESS',
  REMOVE_CLUSTER_DIAGRAM_ELEMENTS_FAILURE:
    'REMOVE_CLUSTER_DIAGRAM_ELEMENTS_FAILURE',

  ADD_CLUSTER_DIAGRAM_NODE_START: 'ADD_CLUSTER_DIAGRAM_NODE_START',
  ADD_CLUSTER_DIAGRAM_NODE_SUCCESS: 'ADD_CLUSTER_DIAGRAM_NODE_SUCCESS',
  ADD_CLUSTER_DIAGRAM_NODE_FAILURE: 'ADD_CLUSTER_DIAGRAM_NODE_FAILURE',

  UPDATE_CLUSTER_DIAGRAM_NODE_START: 'UPDATE_CLUSTER_DIAGRAM_NODE_START',
  UPDATE_CLUSTER_DIAGRAM_NODE_SUCCESS: 'UPDATE_CLUSTER_DIAGRAM_NODE_SUCCESS',
  UPDATE_CLUSTER_DIAGRAM_NODE_FAILURE: 'UPDATE_CLUSTER_DIAGRAM_NODE_FAILURE',

  REMOVE_CLUSTER_DIAGRAM_NODE_START: 'REMOVE_CLUSTER_DIAGRAM_NODE_START',
  REMOVE_CLUSTER_DIAGRAM_NODE_SUCCESS: 'REMOVE_CLUSTER_DIAGRAM_NODE_SUCCESS',
  REMOVE_CLUSTER_DIAGRAM_NODE_FAILURE: 'REMOVE_CLUSTER_DIAGRAM_NODE_FAILURE',

  ADD_CLUSTER_DIAGRAM_PORT_START: 'ADD_CLUSTER_DIAGRAM_PORT_START',
  ADD_CLUSTER_DIAGRAM_PORT_SUCCESS: 'ADD_CLUSTER_DIAGRAM_PORT_SUCCESS',
  ADD_CLUSTER_DIAGRAM_PORT_FAILURE: 'ADD_CLUSTER_DIAGRAM_PORT_FAILURE',

  UPDATE_CLUSTER_DIAGRAM_PORT_START: 'UPDATE_CLUSTER_DIAGRAM_PORT_START',
  UPDATE_CLUSTER_DIAGRAM_PORT_SUCCESS: 'UPDATE_CLUSTER_DIAGRAM_PORT_SUCCESS',
  UPDATE_CLUSTER_DIAGRAM_PORT_FAILURE: 'UPDATE_CLUSTER_DIAGRAM_PORT_FAILURE',

  REMOVE_CLUSTER_DIAGRAM_PORT_START: 'REMOVE_CLUSTER_DIAGRAM_PORT_START',
  REMOVE_CLUSTER_DIAGRAM_PORT_SUCCESS: 'REMOVE_CLUSTER_DIAGRAM_PORT_SUCCESS',
  REMOVE_CLUSTER_DIAGRAM_PORT_FAILURE: 'REMOVE_CLUSTER_DIAGRAM_PORT_FAILURE',

  ADD_CLUSTER_DIAGRAM_LINK_START: 'ADD_CLUSTER_DIAGRAM_LINK_START',
  ADD_CLUSTER_DIAGRAM_LINK_SUCCESS: 'ADD_CLUSTER_DIAGRAM_LINK_SUCCESS',
  ADD_CLUSTER_DIAGRAM_LINK_FAILURE: 'ADD_CLUSTER_DIAGRAM_LINK_FAILURE',

  UPDATE_CLUSTER_DIAGRAM_LINK_START: 'UPDATE_CLUSTER_DIAGRAM_LINK_START',
  UPDATE_CLUSTER_DIAGRAM_LINK_SUCCESS: 'UPDATE_CLUSTER_DIAGRAM_LINK_SUCCESS',
  UPDATE_CLUSTER_DIAGRAM_LINK_FAILURE: 'UPDATE_CLUSTER_DIAGRAM_LINK_FAILURE',

  REMOVE_CLUSTER_DIAGRAM_LINK_START: 'REMOVE_CLUSTER_DIAGRAM_LINK_START',
  REMOVE_CLUSTER_DIAGRAM_LINK_SUCCESS: 'REMOVE_CLUSTER_DIAGRAM_LINK_SUCCESS',
  REMOVE_CLUSTER_DIAGRAM_LINK_FAILURE: 'REMOVE_CLUSTER_DIAGRAM_LINK_FAILURE'
};

export default DiagramActionTypes;
