const DashboardActionTypes = {
  FETCH_OVERALL_STATISTICS_START: 'FETCH_OVERALL_STATISTICS_START',
  FETCH_OVERALL_STATISTICS_SUCCESS: 'FETCH_OVERALL_STATISTICS_SUCCESS',
  FETCH_OVERALL_STATISTICS_FAILURE: 'FETCH_OVERALL_STATISTICS_FAILURE'
};

export default DashboardActionTypes;
